//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class SQLException
    {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState
        {
            get
            {
                return this.sQLStateField;
            }
            set
            {
                this.sQLStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException
        {
            get
            {
                return this.nextExceptionField;
            }
            set
            {
                this.nextExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class sqlException : exception
    {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException
        {
            get
            {
                return this.nextExceptionField;
            }
            set
            {
                this.nextExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class exception : throwable
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class throwable
    {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class stackTraceElement
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="BankService.banque_service")]
    public interface banque_service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/RetirerMontantRequest", ReplyAction="http://service/banque_service/RetirerMontantResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.RetirerMontantResponse> RetirerMontantAsync(BankService.RetirerMontantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/DecryptStringRequest", ReplyAction="http://service/banque_service/DecryptStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.DecryptStringResponse> DecryptStringAsync(BankService.DecryptStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/VerserMontantRequest", ReplyAction="http://service/banque_service/VerserMontantResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.VerserMontantResponse> VerserMontantAsync(BankService.VerserMontantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/AccountExistsRequest", ReplyAction="http://service/banque_service/AccountExistsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.SQLException), Action="http://service/banque_service/AccountExists/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.AccountExistsResponse> AccountExistsAsync(BankService.AccountExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/GetAccountRequest", ReplyAction="http://service/banque_service/GetAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.GetAccountResponse> GetAccountAsync(BankService.GetAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/DeleteAccountRequest", ReplyAction="http://service/banque_service/DeleteAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.DeleteAccountResponse> DeleteAccountAsync(BankService.DeleteAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/EncryptStringRequest", ReplyAction="http://service/banque_service/EncryptStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.EncryptStringResponse> EncryptStringAsync(BankService.EncryptStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/CreateAccountRequest", ReplyAction="http://service/banque_service/CreateAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.CreateAccountResponse> CreateAccountAsync(BankService.CreateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/UpdateAccountRequest", ReplyAction="http://service/banque_service/UpdateAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.UpdateAccountResponse> UpdateAccountAsync(BankService.UpdateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/banque_service/ConvertEuroToDinarRequest", ReplyAction="http://service/banque_service/ConvertEuroToDinarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BankService.ConvertEuroToDinarResponse> ConvertEuroToDinarAsync(BankService.ConvertEuroToDinarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetirerMontant", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class RetirerMontantRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float montant;
        
        public RetirerMontantRequest()
        {
        }
        
        public RetirerMontantRequest(string code, float montant)
        {
            this.code = code;
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetirerMontantResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class RetirerMontantResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public RetirerMontantResponse()
        {
        }
        
        public RetirerMontantResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DecryptString", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class DecryptStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encryptedData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public DecryptStringRequest()
        {
        }
        
        public DecryptStringRequest(string encryptedData, string key)
        {
            this.encryptedData = encryptedData;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DecryptStringResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class DecryptStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public DecryptStringResponse()
        {
        }
        
        public DecryptStringResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerserMontant", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class VerserMontantRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float montant;
        
        public VerserMontantRequest()
        {
        }
        
        public VerserMontantRequest(string code, float montant)
        {
            this.code = code;
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerserMontantResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class VerserMontantResponse
    {
        
        public VerserMontantResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountExists", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class AccountExistsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        public AccountExistsRequest()
        {
        }
        
        public AccountExistsRequest(string code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountExistsResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class AccountExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AccountExistsResponse()
        {
        }
        
        public AccountExistsResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class account
    {
        
        private string codeField;
        
        private float soldeField;
        
        private bool soldeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float solde
        {
            get
            {
                return this.soldeField;
            }
            set
            {
                this.soldeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool soldeSpecified
        {
            get
            {
                return this.soldeFieldSpecified;
            }
            set
            {
                this.soldeFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccount", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class GetAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        public GetAccountRequest()
        {
        }
        
        public GetAccountRequest(string code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class GetAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BankService.account @return;
        
        public GetAccountResponse()
        {
        }
        
        public GetAccountResponse(BankService.account @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAccount", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class DeleteAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        public DeleteAccountRequest()
        {
        }
        
        public DeleteAccountRequest(string code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAccountResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class DeleteAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public DeleteAccountResponse()
        {
        }
        
        public DeleteAccountResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptString", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class EncryptStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public EncryptStringRequest()
        {
        }
        
        public EncryptStringRequest(string data, string key)
        {
            this.data = data;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptStringResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class EncryptStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public EncryptStringResponse()
        {
        }
        
        public EncryptStringResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAccount", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CreateAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float solde;
        
        public CreateAccountRequest()
        {
        }
        
        public CreateAccountRequest(string code, float solde)
        {
            this.code = code;
            this.solde = solde;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAccountResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class CreateAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public CreateAccountResponse()
        {
        }
        
        public CreateAccountResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAccount", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class UpdateAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float solde;
        
        public UpdateAccountRequest()
        {
        }
        
        public UpdateAccountRequest(string code, float solde)
        {
            this.code = code;
            this.solde = solde;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAccountResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class UpdateAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public UpdateAccountResponse()
        {
        }
        
        public UpdateAccountResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertEuroToDinar", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class ConvertEuroToDinarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double montant;
        
        public ConvertEuroToDinarRequest()
        {
        }
        
        public ConvertEuroToDinarRequest(double montant)
        {
            this.montant = montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertEuroToDinarResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class ConvertEuroToDinarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConvertEuroToDinarResponse()
        {
        }
        
        public ConvertEuroToDinarResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface banque_serviceChannel : BankService.banque_service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class banque_serviceClient : System.ServiceModel.ClientBase<BankService.banque_service>, BankService.banque_service
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public banque_serviceClient() : 
                base(banque_serviceClient.GetDefaultBinding(), banque_serviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.banque_servicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public banque_serviceClient(EndpointConfiguration endpointConfiguration) : 
                base(banque_serviceClient.GetBindingForEndpoint(endpointConfiguration), banque_serviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public banque_serviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(banque_serviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public banque_serviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(banque_serviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public banque_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.RetirerMontantResponse> BankService.banque_service.RetirerMontantAsync(BankService.RetirerMontantRequest request)
        {
            return base.Channel.RetirerMontantAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.RetirerMontantResponse> RetirerMontantAsync(string code, float montant)
        {
            BankService.RetirerMontantRequest inValue = new BankService.RetirerMontantRequest();
            inValue.code = code;
            inValue.montant = montant;
            return ((BankService.banque_service)(this)).RetirerMontantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.DecryptStringResponse> BankService.banque_service.DecryptStringAsync(BankService.DecryptStringRequest request)
        {
            return base.Channel.DecryptStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.DecryptStringResponse> DecryptStringAsync(string encryptedData, string key)
        {
            BankService.DecryptStringRequest inValue = new BankService.DecryptStringRequest();
            inValue.encryptedData = encryptedData;
            inValue.key = key;
            return ((BankService.banque_service)(this)).DecryptStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.VerserMontantResponse> BankService.banque_service.VerserMontantAsync(BankService.VerserMontantRequest request)
        {
            return base.Channel.VerserMontantAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.VerserMontantResponse> VerserMontantAsync(string code, float montant)
        {
            BankService.VerserMontantRequest inValue = new BankService.VerserMontantRequest();
            inValue.code = code;
            inValue.montant = montant;
            return ((BankService.banque_service)(this)).VerserMontantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.AccountExistsResponse> BankService.banque_service.AccountExistsAsync(BankService.AccountExistsRequest request)
        {
            return base.Channel.AccountExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.AccountExistsResponse> AccountExistsAsync(string code)
        {
            BankService.AccountExistsRequest inValue = new BankService.AccountExistsRequest();
            inValue.code = code;
            return ((BankService.banque_service)(this)).AccountExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.GetAccountResponse> BankService.banque_service.GetAccountAsync(BankService.GetAccountRequest request)
        {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.GetAccountResponse> GetAccountAsync(string code)
        {
            BankService.GetAccountRequest inValue = new BankService.GetAccountRequest();
            inValue.code = code;
            return ((BankService.banque_service)(this)).GetAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.DeleteAccountResponse> BankService.banque_service.DeleteAccountAsync(BankService.DeleteAccountRequest request)
        {
            return base.Channel.DeleteAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.DeleteAccountResponse> DeleteAccountAsync(string code)
        {
            BankService.DeleteAccountRequest inValue = new BankService.DeleteAccountRequest();
            inValue.code = code;
            return ((BankService.banque_service)(this)).DeleteAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.EncryptStringResponse> BankService.banque_service.EncryptStringAsync(BankService.EncryptStringRequest request)
        {
            return base.Channel.EncryptStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.EncryptStringResponse> EncryptStringAsync(string data, string key)
        {
            BankService.EncryptStringRequest inValue = new BankService.EncryptStringRequest();
            inValue.data = data;
            inValue.key = key;
            return ((BankService.banque_service)(this)).EncryptStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.CreateAccountResponse> BankService.banque_service.CreateAccountAsync(BankService.CreateAccountRequest request)
        {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.CreateAccountResponse> CreateAccountAsync(string code, float solde)
        {
            BankService.CreateAccountRequest inValue = new BankService.CreateAccountRequest();
            inValue.code = code;
            inValue.solde = solde;
            return ((BankService.banque_service)(this)).CreateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.UpdateAccountResponse> BankService.banque_service.UpdateAccountAsync(BankService.UpdateAccountRequest request)
        {
            return base.Channel.UpdateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.UpdateAccountResponse> UpdateAccountAsync(string code, float solde)
        {
            BankService.UpdateAccountRequest inValue = new BankService.UpdateAccountRequest();
            inValue.code = code;
            inValue.solde = solde;
            return ((BankService.banque_service)(this)).UpdateAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankService.ConvertEuroToDinarResponse> BankService.banque_service.ConvertEuroToDinarAsync(BankService.ConvertEuroToDinarRequest request)
        {
            return base.Channel.ConvertEuroToDinarAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.ConvertEuroToDinarResponse> ConvertEuroToDinarAsync(double montant)
        {
            BankService.ConvertEuroToDinarRequest inValue = new BankService.ConvertEuroToDinarRequest();
            inValue.montant = montant;
            return ((BankService.banque_service)(this)).ConvertEuroToDinarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.banque_servicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.banque_servicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return banque_serviceClient.GetBindingForEndpoint(EndpointConfiguration.banque_servicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return banque_serviceClient.GetEndpointAddress(EndpointConfiguration.banque_servicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            banque_servicePort,
        }
    }
}
